export {default as Basket} from "./Basket"
export {default as Contact} from "./Contact"
export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as SingleProducts} from "./SingleProducts"
export {default as Login} from "./Login"
export {default as Register} from "./Register"